package ex_30_Exceptions;

public class Lab130_TryCatchMultiple2 {
    public static void main(String[] args) {
        try {
            int a = 10 / 0;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
